# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71c3b006d4f55763681f23e9bb1f39db6d4e6ce8652ab39375cb07016e5bfd27a9b717d35b38b76703f8052487f32360df7f015e9a7dd48d3956297e6c8c61b0

test:
  secret_key_base: bd93412f35f3003ad3923c286ab9e60d10002c183bc2c818c66ede37e085fd198c31eca2bc9eaf956ad0bec00b73badfb238da1374a713fe1508db68a1eb7e32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
